unbind C-b
set -g prefix C-q
source-file '.config/tmux/themes/tomorrow.tmux'
#bind-key j select-pane -D
#bind-key k select-pane -U
set -g monitor-activity on
set -g visual-activity on
# Set zsh as default shell
set -g default-shell /usr/bin/zsh

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin "soyuka/tmux-current-pane-hostname"

#set -g mouse off
# Plugins configuration

#set -g @url-view 'u'
#run '/home/anon/.tmux/plugins/tpm/tpm'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
